source 'https://rubygems.org'

gem 'rails', '3.2.1'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'mysql2'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer'
  
  gem 'uglifier', '>= 1.0.3'
end

gem 'foreigner'
gem 'twitter-bootstrap-rails'
gem 'sorcery'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'carrierwave'  
gem 'google_visualr', ">= 2.1"
gem 'client_side_validations'
gem 'rails3-jquery-autocomplete'
gem 'prawn',  git: 'https://github.com/prawnpdf/prawn.git'
gem "prawnto_2", :require => "prawnto"
gem 'jquery-rails', "~> 2.1"
gem 'yaml_db'
gem 'calendar_date_select'
gem 'simple_audit', "~> 0.2.0"
gem "audited-activerecord", "~> 3.0"
gem "audited-mongo_mapper", "~> 3.0"
# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug19', :require => 'ruby-debug'
