require 'custom_logger'

class HelpsController < ApplicationController
  
  def index
    @link = [
      "Como ingresar al Sistema de Ventas?",
      "Como registrar un Cliente?",
      "Como ver e imprimir o descargar la Lista de Cliente?",
      "Como registrar una Localidad?",
      "Como ver la Lista de Localidades?",
      "Como registrar un Departamento?",
      "Como ver la Lista de Departamentos?",
      "Como registrar una Venta/Facturacion?",
      "Como ver e imprimir o descargar la Lista de Facturas?",
      "Como registrar un Producto?",
      "Como ver e imprimir o descargar la Lista de Productos?",
      "Como generar un Movimiento de Stock (Entrada/Salida)?",
      "Como ver e imprimir o descargar Reporte de Clientes?",
      "Como ver e imprimir o descargar Reporte de Productos?",
      "Como ver e imprimir o descargar Reporte de Ventas?",
      "Como ver y actualizar Datos de la Empresa?",
      "Como registrar un Usuario?",
      "Como ver la Lista de Usuarios?",
      "Como registrar Funcionario?",
      "Como ver la Lista de Funcionarios?",
      "Como ver el log de Auditoria?"
    ]
    @link_helps=[
      "En donde indica Registrarse, debes completar correctamente los campos de Usuario y Contrasena, una vez completo haz click en Ingresar y ya estaras habilitado para utilizar el Sistema de Ventas, si necesitas adquirir conocimientos acerca del Sistema haz click en Ayuda; recuerda que para estar registrado como un Usuario el Administrador del Sistema debe registrarte como un funcionario y luego como un usuario.",
      "Ir al Menu,Cliente, Clikc en Nuevo Cliente. Aqui debes completar todos los datos requeridos del cliente, si no se encuentra registrada su Localidad tenes la opcion de crear una Nueva Localidad desde aca, una vez completo haz click en Guardar, esto te redirecciona a una tabla donde te muestra todos los datos del Nuevo Cliente en donde tenes la opcion de editar o borrar los datos del mismo si fuera necesario.Tambien desde aca tenes la opcion de Crear un Nuevo Cliente o ir a la Lista Completa de Clientes. Si haces click en Cancelar te llevara a la Lista Completa de Clientes registrados en la Empresa. Para realizar dicha accion de registrar debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Cliente, Clikc en Lista de Clientes. Aqui muestra todos los datos de los Clientes registrados en la Empresa, teniendo la opcion de editar o borrar datos de uno o mas clientes si fuera necesario. Tambien desde aca tenes la opcion de Crear un Nuevo Cliente o de Ver la Lista Completa en formato PDF,pudiendo descargarlo, o imprimir desde la web si lo desea. Para realizar dicha accion de ver o imprimr debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Cliente,Localidad, Clikc en Nueva Localidad. Aqui debes completar todos los datos requeridos de la localidad, si no se encuentra registrado el Departamento al que pertenece tenes la opcion de crear un Nuevo Departamento desde aca,una vez completo haz click en Guardar, esto te redirecciona a una tabla donde te muestra todos los datos de la Nueva Localidad en donde tenes la opcion de editar o borrar los datos del mismo si fuera necesario. Tambien desde aca tenes la opcion de Crear una Nueva Localidad o ir a la Lista Completa de Localidades.Si haces click en Cancelar te llevara a la Lista Completa de Localidades registradas en la Empresa. Para realizar dicha accion de registrar debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Cliente,Localidad, Clikc en Lista de Localidades. Aqui muestra todos los datos de las Localidades registradas en la Empresa, teniendo la opcion de editar o borrar datos de una o mas Localidades si fuera necesario. Tambien desde aca tenes la opcion de Crear una Nueva Localidad. Para realizar dicha accion de ver debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Cliente,Departamento, Clikc en Nuevo Departamento. Aqui debes completar todos los datos requerido del departamento, una vez completo haz click en Guardar, esto te redirecciona a una tabla donde te muestra todos los datos de Nuevo Departamento en donde tenes la opcion de editar o borrar los datos del mismo si fuera necesario. Tambien desde aca tenes la opcion de Crear un Nuevo Departamento o ir a la Lista Completa de Departamentos.Si haces click en Cancelar te llevara a la Lista Completa de Departamentos registrados en la Empresa. Para realizar dicha accion de registrar debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Cliente, Departamento, Clikc en Lista de Departamentos. Aqui muestra todos los datos de los Departamentos registrados en la Empresa, teniendo la opcion de editar o borrar los datos de uno mas departamento si fuera necesario. Tambien desde aca tenes la opcion de Crear un Nuevo Departamento. Para realizar dicha accion de ver debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Facturacion, Clikc en Nueva Factura. Aqui en el campo Cliente debes empezar a escribir el nombre del cliente y ya te ira autocompletando los mismos, debes seleccionar el cliente para tu factura, en el caso de que el cliente no este registrado tienes la opcion de crear Nuevo Cliente a partir de aca, los demas campos de la parte superior de la factura ya estan completos. Ahora para cargar Productos a la factura debes ir hasta la opcion Cargar Producto, haz click sobre el mismo, aqui te muestra tres campos a completar, en el campo Producto tambien debes ir autocompletando el nombre del producto luego selecciona el producto deseado,  en el campo Cantidad ingresa la cantidad  y en el campo Descuento el descuento del mismo, una vez completos correctamente estos datos haz Click en Guardar, lo que hara ahi es actualizar en la lista de productos  que acabas de ingresar. En el caso de que se quiera eliminar o editar un prodcuto  ya seleccionado se tiene la opcion en la misma tabla. En la parte inferior de la Factura a medida que agreguemos los productos nos ira completando de forma automatica el Total IVA, Total Descuento, y Total en la moneda local Gs. Continuamente que esto tenes la opcion de Guardar o Cancelar dicha factura, donde Guardar te guarda la factura en cuestion y si se selecciona Cancelar te lleva a la Lista de Facturas. Para realizar dicha accion de registrar debes ser un Administrativo o Empleado de la Empresa.  ",
      "Ir al Menu,Facturacion, Clikc en Lista de Facturas. Aqui puedes ver la Lista de facturas realizadas por la empresa, teniendo la opcion de anular una o mas facturas si fuera necesario. Para realizar dicha accion de ver o imprimir debes ser un Administrativo o Empleado de la Empresa.  ",
      "Ir al Menu,Producto, Clikc en Nuevo Producto. Aqui debes completar todos los datos requeridos del producto, una vez completo haz click en Guardar, esto te redirecciona a una tabla donde te muestra todos los datos de Nuevo Producto en donde tenes la opcion de editar o borrar los datos del mismo si fuera necesario. Tambien desde aca tenes la opcion de Crear un Nuevo Producto o ir a la Lista Completa de Productos.Si haces click en Cancelar te llevara a la Lista Completa de Productos registrados en la Empresa. Para realizar dicha accion de registrar debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Producto, Clikc en Lista de Productos. Aqui muestra todos los datos de los Productos registrados en la Empresa, teniendo la opcion de editar o borrar los datos de uno mas productos si fuera necesario. Tambien desde aca tenes la opcion de Crear un Nuevo Producto o de Ver la Lista Completa en formato PDF,pudiendo descargarlo, o imprimir desde la web si lo desea. Para realizar dicha accion de ver o imprimir debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Producto, Clikc en Movimiento de Stock. Aqui debes completar todos los datos requeridos del moviento de stock a realizar, selecciona el tipo de moviento, agregale una descripcion a tu movimiento, luego haz click en el icono de Cargar Producto: aqui debes completar todos los datos del producto del cual desea realizar un movimiento, luego haza click en Guardar; una vez completo ya todos los datos haz click en Guardar, esto te redirecciona a una tabla donde te muestra todos los datos del Movimiento de Stock que acabas de realizar en donde tenes la opcion de editar o borrar los datos del mismo si fuera necesario. Tambien desde aca tenes la opcion de Crear un Movimiento de Stock o ir a la Lista Completa de los mismos.Si haces click en Cancelar te llevara a la Lista Completa de Movimientos de Stock registrados en la Empresa. Para realizar dicha accion de registrar debes ser un Administrativo de la Empresa.",
      "Ir al Menu,Reporte,Listado, Clikc en Clientes. Aqui muestra todos los datos de los Clientes registrados en la Empresa en un documento de fomrato PDF, teniendo la opcion de descargar o imprimir directamente desde la web. Para realizar dicha accion de ver o imprimir debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Reporte,Listado, Clikc en Productos. Aqui muestra todos los datos de los Productos registrados en la Empresa en un documento de fomrato PDF, teniendo la opcion de descargar o imprimir directamente desde la web. Para realizar dicha accion de ver o imprimir debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Reporte,Listado, Clikc en Ventass. Aqui muestra todos los datos de las Ventas registradas en la Empresa en un documento de fomrato PDF, teniendo la opcion de descargar o imprimir directamente desde la web. Para realizar dicha accion de ver o imprimir debes ser un Administrativo o Empleado de la Empresa.",
      "Ir al Menu,Configuracion del Sistema, Datos de la Empresa, Clikc en Ver Datos. Aqui los datos actuales de la Empresa, teniendo la opcion de editar si fuera necesario los mismos. Si deseas actualizar los datos de la Empresa haz click en Editar,Aqui selecciona la nueva imagen de la empresa, y completa todos los datos requeridos, una vez completo todos los datos haz click en Guardar. Si no deseas actualizar los datos haz click en Cancelar, esto te llevara a la tabla de datos actuales de tu empresa.Para realizar dicha accion de ver debes ser un Administrativo de la Empresa.",
      "Ir al Menu,Configuracion del Sistema, Usuario, Click en Nuevo Usuario. Aqui debes completar todos los datos requeridos del usuario, si no se encuentra registrado el Funcionario al corresponde tenes la opcion de crear un Nuevo Funcionario desde aca,una vez completo haz click en Guardar, esto te redirecciona a una tabla donde te muestra todos los datos del Nuevo Usuario en donde tenes la opcion de editar o borrar los datos del mismo si fuera necesario. Tambien desde aca tenes la opcion de Crear un Nuevo Usuario o ir a la Lista Completa de Usuarios.Si haces click en Cancelar te llevara a la Lista Completa de Usuarios registradas en la Empresa. Para realizar dicha accion de registrar debes ser un Administrativo de la Empresa.",
      "Ir al Menu,Configuracion del Sistema, Usuario, Clikc en Lista de Usuarios. Aqui muestra todos los datos de los Usuarios registrados en la Empresa, teniendo la opcion de editar o borrar datos de uno o mas Usuarios si fuera necesario. Tambien desde aca tenes la opcion de Crear un Nuevo Usuario. Para realizar dicha accion de ver debes ser un Administrativo de la Empresa.",
      "Ir al Menu,Configuracion del Sistema, Funcionario, Click en Nuevo Funcionario. Aqui debes completar todos los datos requeridos del funcionario, si no se encuentra registrado la Localidad al corresponde tenes la opcion de crear una Nueva Localidad desde aca,una vez completo haz click en Guardar, esto te redirecciona a una tabla donde te muestra todos los datos del Nuevo Funcionario en donde tenes la opcion de editar o borrar los datos del mismo si fuera necesario. Tambien desde aca tenes la opcion de Crear un Nuevo Funcionario o ir a la Lista Completa de Funcionarios.Si haces click en Cancelar te llevara a la Lista Completa de Funcionarios registradas en la Empresa. Para realizar dicha accion de registrar debes ser un Administrativo de la Empresa.",
      "Ir al Menu,Configuracion del Sistema, Funcionario, Clikc en Lista de Funcionarios. Aqui muestra todos los datos de los Funcionarios registrados en la Empresa, teniendo la opcion de editar o borrar datos de uno o mas Funcionarios si fueranecesario. Tambien desde aca tenes la opcion de Crear un Nuevo Funcionario. Para realizar dicha accion de ver debes ser un Administrativo de la Empresa.",
      "Ir al Menu,Configuracion del Sistema, Auditoria, Click en Detalle de Auditoria. Aqui muestra puede ver el Log completo de Auditoria: con fecha, hora, actividad realizada y el usuario responsable. Para realizar dicha accion de ver debes ser un Administrativo de la Empresa.  ",
    ]
  end
  
end